apiVersion: v2
name: Totp-binder-service
description: A Helm chart for MOSIP Totp-binder-service module
type: application
version: 1.2.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - Totp-binder-service
maintainers:
  - email: info@mosip.io
    name: MOSIP
